[package]
name = "gluestick"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = { version = "0.12.1", features = ["with-axum"] }
askama_axum = "0.4.0"
axum = "0.7.5"
dotenvy = "0.15.7"
include_dir = "0.7.3"
rusqlite = { version = "0.31.0", features = ["bundled"] }
rusqlite_migration = { version = "1.2.0", features = ["from-directory", "alpha-async-tokio-rusqlite"] }
serde = { version = "1.0.198", features = ["derive"] }
thiserror = "1.0.59"
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread", "signal"] }
tokio-rusqlite = "0.5.1"
tower-http = { version = "0.5.2", features = ["trace", "fs"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18" }
