# This is the config file for cargo-deny
# https://github.com/EmbarkStudios/cargo-deny

# This section is considered when running `cargo deny check advisories`
# https://embarkstudios.github.io/cargo-deny/checks/advisories/cfg.html
[advisories]

# A list of advisory IDs to ignore. Note that ignored advisories will still
# output a note when they are encountered.
ignore = [
    { id = "RUSTSEC-2024-0320", reason = "Syntect uses yaml-rust, which is unmaintained, though they intend to upgrade to yaml-rust2 in v6.0.0. For now, this is fine." },
]

# This section is considered when running `cargo deny check licenses`
# https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html
[licenses]

allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
]

# Allow 1 or more licenses on a per-crate basis, so that particular licenses
# aren't accepted for every possible crate as with the normal allow list
exceptions = [
    { allow = ["Unicode-DFS-2016"], crate = "unicode-ident" },
]
