version: 2.1

parameters:
  rust-version:
    type: string
    default: "1.78"
  target-cache-key:
    type: string
    default: "target-{{ arch }}-{{ checksum \"Cargo.lock\" }}"
  cargo-deny-version:
    type: string
    default: "0.14.24"
  cargo-deny-cache-key:
    type: string
    default: "cargo-deny-test1-{{ arch }}-0.14.24"

jobs:
  lint-and-test:
    docker:
      - image: cimg/rust:<< pipeline.parameters.rust-version >>
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Formatting
          command: cargo fmt --check
      - restore_cache:
          keys:
            - << pipeline.parameters.target-cache-key >>
      - run:
          name: Linting
          command: cargo clippy --locked -- -D warnings
      - run:
          name: Testing
          command: cargo test --locked
      - save_cache:
          paths:
            - ./target
          key: << pipeline.parameters.target-cache-key >>

  audit:
    docker:
      - image: cimg/rust:<< pipeline.parameters.rust-version >>
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - restore_cache:
          keys:
            - << pipeline.parameters.cargo-deny-cache-key >>
      - run:
          name: Debug
          command: ls -la /home/circleci/.cargo/bin/cargo
      - run:
          name: Installing cargo deny
          command: cargo install cargo-deny@<< pipeline.parameters.cargo-deny-version >> --locked
      - run:
          name: Debug
          command: ls -la /home/circleci/.cargo/bin/cargo
      - save_cache:
          paths:
            - /home/circleci/.cargo/bin/cargo
          key: << pipeline.parameters.cargo-deny-cache-key >>
      - run:
          name: Advisories auditing
          command: cargo deny check advisories
      - run:
          name: Licenses auditing
          command: cargo deny check licenses

workflows:
  main:
    jobs:
      - lint-and-test
      - audit
